= applstdef_emC.h in emC
:toc:
:sectnums:
:sectlinks:
:cpp: C++

== Content of applstdef_emC

This file contains some compiler switch definitions and maybe an implementation specifically selection of general header files to support a platform unspecific programming of the user's application using the *_emC_* approach. 

This file is not necessary for driver and unspecific platform adaptions, elsewhere this files uses exception handling. For exception handling it is necessary to decide through the `applstdef_emC.h` which approach is used. 

If the `applstdef_emC.h` is included in common library sources. Hence this compilation units should be compiled application specific. It is not usefull to store it in an unspecific library. Because: The behavior is even controlled by the application specific `applstdef_emC.h`. Hence a pre-compiled library concept is not adequate for the *_emC_* concept. Libraries can be used to leave it up to the linker to select the necessary objects for a build. But the libraries should be build specific for the application with the given associated `applstdef_emC.h`.

== Selection of Granulatity of the ObjectJc base class

The `ObjectJc` base class can be used for 'struct` definitions to check the instance's type and to get reflection information. `ObjectJc` can be elaborately used for test platforms because it can refer all symbolic information about the struct's elements. But for an implementation in a simple 'poor' platform it can be reduced at least to only one `int32` value. Of course symbolic information cannot be gotten then, and the type test is reduced to only a number for comparison. But if the platform is 'poor' (less memory) it shouln't be necessary. The important fact is, that a reused library source can be used without change.

In the `applstdef_emC.h` there is decide about the features of `ObjectJc` 

 /**Define the granularity of the ObjectJc base class: */
 #define DEF_ObjectSimple_emC
 #define DEF_ObjectJc_SIMPLE
 //#define DEF_ObjectJc_REFLREF
 //#define DEF_ObjectJc_SYNCHANDLE
 //#define DEF_ObjectJcpp_REFLECTION
 //#define DEF_ObjectJc_OWNADDRESS
 //#define DEF_ObjectJc_LARGESIZE

Some defines should be activated, some are commented. 

* `DEF_ObjectSimple_emC` decides that in a 

 #included <emC/Base/Object_emC.h>
 
only the file `emC/Base/ObjectSimple_emC.h` is included, and not the more complex `emC/Base/ObjectRefl_emC.h`. It means that the users project should not know a lot of files from the *_emC_* source pool. Only the `emC/Base/ObjectSimple_emC.h` is necessary.

The `emC/Base/ObjectSimple_emC.h` can define the `ObjectJc` class:

* either as simplest

 typedef struct  ObjectJc_T
 { uint32 identSize;
 } ObjectJc;
 
or with defined `DEF_ObjectJc_REFLREF` including a reference to a 

 typedef struct  ObjectJc_T
 { uint32 identSize;
   struct ClassJc_t const* reflection;
 } ObjectJc;

The `ClassJc` 
