= Usage of the ObjectJc base class in C and {cpp} applications
:toc:
:sectnums:
:sectlinks:
:cpp: C++

[#ObjectJc]
== What is ObjectJc

The struct `ObjectJc` is a basic struct that can be used for all data instances 
(`struct` and `class`) with some common maybe important information with less effort. 
The information is at least:

* An identifier for the type, important for type check on downcast.
* Information about initialized status: init or run, one bit. An instance should be
switched to the run mode if all aggregations are complete.
* Size information.

For these three pieces of information only 4 Byte (an `uint32_t`) is necessary;

 //in src_emC/emC/Base/Object_emC.h:
 typedef struct  ObjectJc_T
 {
  /**The identSize is helpfull to recognize the instance. 
   * The bit31 is used to detect whether it is initialized or not. */
  uint32 identSize;
  #define mInitialized_ObjectJc  0x80000000
  #define mInstanceType_ObjectJc 0x7fff0000  
  #define kBitInstanceType_ObjectJc 16
  #define mSize_ObjectJc         0x0000ffff
  
For usage of `ObjectJc` in a {cpp} context with symbolic information about fields
in the derived class an additional offset between start of the data class
and position of the `ObjectJc` inside the data are necessary. Additionally a field
for handle values is intended here. This both fields are available if the following
compiler switch is set:

  #ifdef DEF_ObjectJcpp_REFLECTION
    /**Offset from the data-instance start address to the ObjectJc part. 
     * It is especially for symbolic field access (reflection) in {cpp}. */
    uint16 offsetToStartAddr;
    /**Some handle bits to use an ObjectJc for lock (mutex). */
    uint16 handleBits;
    #define kNoSyncHandles_ObjectJc 0x0fff;
  #endif

In this case, but also independently if `DEF_ObjectJc_REFLREF` is defined,
a reference from `ObjectJc` to `ClassJc` named `reflection` is available.
This improves the type test capability, especially recognizing base type references 
(derivation), and it opens the possibility to support full symbolic information 
about the fields in the data. It is the 'reflection' capability, see link:ClassJc_en.html[].  

  #if defined(DEF_ObjectJc_REFLREF) || defined(DEF_ObjectJcpp_REFLECTION)
    #define mInstance_ObjectJc 0x7fff0000
    #define kBitInstance_ObjectJc 16
    /**The reference to the type information. */
    struct ClassJc_t const* reflection;
  #endif

If a `ClassJc` instance can be referenced, the identifier in the first word 
`identSize` is now used as  instance identifier. 

Last not least the own address of the Object can be stored in the ObjectJc.
The address of itself can be used if data are copied to any file (a memory map), 
and references between the data should be readjusted. 

  #ifdef DEF_ObjectJc_OWNADDRESS
    void const* ownAddress;
  #endif
 } ObjectJc;

Depending on the memory layout the reflection and the ownAddress has 2 Byte 
(in 16-bit-Systems), 4 Byte or 8 Byte (for 64-bit-Adressing). In all cases the alignment
is correct. Note that 64-bit-addresses should aligned to a memory word boundary wich is usually 8 Byte.

The idea for `ObjectJc` came from Java. In Java all instances have a base ('_super_')
class `java.lang.Object` with adequate information. It is a proven concept.


== Using ObjectJc for C struct

A C struct for C and {cpp} compilation should be defined as:

 typedef struct MyData_T {
   union { MyBaseData super; ObjectJc obj; } base;
   int32_t anyData;
 } MyData_s;
 
* The usage of `typedef` is recommended. Some compilers expect it, it is the clarified form.

* The `MyData_T` is the tag name. The tag name should not be the same as the type name, 
some compilers may have problems elsewhere! It can be used for forward-declaration.

 struct MyData_T;
 ....
 extern struct MyData_T anyData; //data are only declared
 .....
 struct MyData_T* ref = getRef(...)  //only use the reference without access
 
* The type name `MyData_s` is written with suffix `_s` to offer the possibility
for a wrapping {cpp} class which should be named `MyData`. 
This writing rules are regarded by link:ClassJc_en.html#Header2Refl[ClassJc_en, chapter "The reflection generator"].

The `ObjectJc` is arranged as the last or only one element inside a union. The other parts
of the union should be base `struct` (super `struct`), 
whereby the immediate super `struct` should be arranged first, necessary for
`INIZ_...` initialization with `{ ... }`. 
This writing rule enables the access to `ObjectJc` in an unified form independent
of super `struct` nesting (inheritance in C) writing:

 ObjectJc* obj = &myDataRef->base.obj;
 
For C usage it is the same as a simple pointer casting `((ObjectJc*)myDataRef)`
because the ObjectJc is the first part in memory. 
But usage pointer castings is not recommended because it is an additional 
(supposed unsafe) cast. Secondly it may be faulty if `myDataRef` is a {cpp} class
where the `ObjectJc` is member of. 
Unnecessary casting is an example of dirty software which runs
some years, then somebody extends it, and the assumption for the cast is no longer true.
Hence an important rule for C-programming is: "*Avoid unchecked casting of pointers!*". 



== Using ObjectJc in {cpp} classes

It is possible and recommended define the data of a {cpp} class as C-`struct` . 
Then this `struct` contains `ObjectJc` in the form above.   

There are generally three forms to inherit from a C-`struct`:

 class MyData: public MyData_s { ... 

with possible access to data and immediately to `myDatab->base.obj`.

 class MyData: proctected MyData_s { 
   ... 
   public: ObjectJc const* toObject() {
     return this->base.obj; 
   }
   
It has protected access to the data, but a individual operation `toObject()` 
which returns the `ObjectJc const*` reference only to the read only `ObjectJc` data.
This form does not need virtual operations for that.

 class MyData: public ObjectJcpp, proctected MyData_s { 
   ... 
   public: ObjectJc const* toObject() {
     return this->base.obj; 
   }

The interface `ObjectJcpp` contains the operation `toObject()` as virtual, 
hence a reference of type `ObjectJcpp` is generally useable to access the `ObjectJc` data. 
But this form needs virtual operations, it may not be desired in some embedded applications.

It is a question of {cpp} using philosophy: 

* If {cpp} should be used only because of some {cpp} language features, for example
operator definition (`float operator+(...)`),
but virtual operations are forbidden by style guide for safety than
the first or second form is appropriate.

* For common {cpp} usage the third form is recommended.


See test sources, it contains some casting situations too: 
`emC_Base/src/test/cpp/emC_Test_ObjectJc/test_ObjectJcpp.cpp`.

[#initC]
== Initializing of data with ObjectJc

[#INIZ]
=== static and const initializing with initializer list in C

To get const data in a const memory section (Flash Rom) only
a `const` initializing can be done with an so named _initializer list_.
Thas is the same situation in C as in {cpp} (!). 

 Type const myData = { ..... };  //hint: write const right side.
 const Type myData = { ..... };  //it is the same
 
In C it is not possible to initialize const data in any operations in runtime, 
other than in {cpp}. The immediately initializing C-style is necessary 
if data should be stored in a const memory section (on Flash-ROM, for embedded Processors). 
This topic is irrelevant for {cpp} programming on a PC platform, 

For non `const` data the same initializing with an _initializer list_
is possible for all non-allocated data (not from heap). 
If static data are used an initializing  may be seen as recommended.

 Type myData;  //The initial data are undefined - prone of error
 Type myData = {0}; //at least forced 0-initialization.
 
An _initializer list_ with given data is often complex to write, it is a challenge for the programmer. Macros to initialize some parts of nested data are helpful.

For example some `struct` may be defined as:

 typedef struct BaseType_T {
   union{ ObjectJc obj;} base;
   int32 data1;
   float data2;
 } Base_Type;
 //
 typedef struct InnerData_T {
   float x,y,z; 
 } InnerData;
 //
 typedef struct MyType_T {
   union { BaseType BaseType; ObjectJc obj; } base;
   int32 m, n;
   InnerData data1;
   int p,q;
 } MyType_s;

then a initializer is complex. 
Especially if some types are defined in another module or component it is difficult to handle. 
At least for ObjectJc a macro `INIZ_ObjectJc` can be used. 
It is recommended to write such an `INIZ...` macro for any type:

 #define INIZ_VAL_BaseType( OBJ, REFL, ID, VAL) \
  { { INIZ_ObjectJc(OBJ, REFL, ID) } \
  , (int32)VAL, (float)VAL \
  }

 #define INIZ_InnerData( ) \
  { 3.14f, 42.0f, -3.0f }  //it is only a const initizalization

 #define INIZ_VAL_MyType( OBJ, ID, VAL1, VAL2) \
 { { INIZ_VAL_MyBaseType(OBJ, refl_MyType, ID, VAL1) } \
 , VAL2, -(VAL2) \
 , INIZ_InnerData() \
 , 0,0 \
 }

This macros should be written near to the struct definitions, to see the association. 

* The arguments of the macro may have a free meaning and order 
But the initializing values have to be able to calculate on compile time.
* Because the `BaseType` has `base.obj`, it uses the `INIZ_ObjectJc(...)`.
* Because the `BaseType` is used as base type, it is necessary to give 
the reflection information as argument `REFL` here.
* The `INIZ_VAL_MyType(...)` does not need information about the data arrangement 
of the inner struct data. It invokes only the `INIZ...` macro of the nested data.
Hence the information about the data arrangement is encapsulated.

* The first `INIZ...` macro inside `INIZ_VAL_MyType(...)` should have a `REFL`-argument. 
Because the `MyType` is never used as base class the reflection are not given as
argument, but they are given immediately. 

The `INIZ_ObjectJc` macro is defined depending on the variants of `ObjectJc` 
in different forms. The arguments are the same in any case. 
As special feature the `REFL` argument is used in case of `DEF_ObjectJc_SIMPLE` as 

 #define INIZ_ObjectJc(OBJ, REFL, ID)  \
 { ((((uint32)(ID_##REFL))<<kBitInstanceType_ObjectJc) & mInstanceType_ObjectJc) \
 | (sizeof(OBJ) & mSize_ObjectJc) \
 }

It means, the identifier for the reflection class is used as identifier 
for the numerical `ID_refl_MyType` because the simple variant of an `ObjectJc` 
has not a reference to the reflection but only the ID. The definition of an

 ClassJc const refl_MyType = INIZ_ClassJc(refl_MyType, "MyType");
 
it not necessary and may not be given if `DEF_REFLECTION_NO` is set. The type-ID 
already stored in a also given `ClassJc const` cannot be used for a const initialization
because it is not able to calculate on compile time:

Getting a `const` value from a given another `const` instance inside an 
initializer list is not possible in C 
and not possible for C++ `const`-memory-segment-initialization. 
The access to `refl->idType` fails though it is a instance defined before. 
It is too complex for the compiler's initializer value calculation.

Adequate it is not possible to use the address of the instance shifted and masked
for the correct bit position. An address value inside a constant initializer list
is only possible by linker replacement, the address value can only be set 
as const reference as a whole from the linker. Some numeric calculations afterwards
cannot be done with it because they would need to be done by the compiler.


[#CTOR]
=== CTOR_/ctor_ObjectJc(...) - initialization on run time 

The `ObjectJc` part on an instance is the core part but it contains information
for the whole instance: The type and size. Hence it should be initialized firstly
with respect to the instance:

 MyType_s data = {0} ; //create in stack with recommended 0-initialization
 CTOR_ObjectJc( &data.base.obj, &data, sizeof(data)
              , refl_MyType, ID_Obj);

Then the construction of the instance can be done:

 ctor_MyType(&data, 42.0f, 234);

The `CTOR_ObjectJc` is a macro which regards `DEF_REFLECTION_NO`. In this case 
it uses the given identifier for the reflection type and invokes

 ctor_ObjectJc(&data.base.obj, &data, sizeof(data), null, ID_refl_MyType);

It does not assume the existence of a `ClassJc` instance. But the `ID_refl...` should be defined, see link:ClassJc_en.html#ID_refl[]. But if a `ClassJc` instance is given anyway,
the 

 ctor_ObjectJc(&data.base.obj, &data, sizeof(data), refl_MyType, ID_Obj);

can be used. In case of `DEF_ObjectJc_SIMPLE` the type-ID is taken from the `ClassJc` 
instance and the `ID_Obj` is not use. 

The constructor of the user types should not invoke the `ctor_ObjectJc(...)`.
Instead a check of consistence can be done, which assures that the given instance
has a proper size and the given type is matching. This can be done as assertion:

 ASSERT_emC( CHECKstrict_ObjectJc( &thiz->base.obj, sizeof(*thiz)
                                 , refl_MyType, 0)
           , "not matching instance and type", 0,0);

It has the advantage that the check-code is not existing if `ASSERT_IGNORE_emC` is set.
On embedded platforms usually the construction is done only on startup. The startup can
be tested well on PC platform with assertion check and with Exception handling, 
so errors are detected on PC-test. 

The `CHECKstrict_ObjectJc(...)` is a macro again which invokes in case of `DEF_REFLECTION_NO`:

 checkStrict_ObjectJc(OTHIZ, SIZE, null, ID_##REFL)
 
It does only test, an Exception is thrown only in conclusion with `ASSERT_emC`.

'''

Some details to the arguments both for ctor_... and CTOR_...

* `REFL` For the reflection argument (See link:#refl[chapter "Reflection and Types"]). 

* `ADDR` The second argument of the ctor `ADDR` is expected of type `void*` and should be the address 
of the instance itself. It has the same value for C-compilation as the `ObjectJc` reference
because `ObjectJc` is the first element in a `struct`.
But for {cpp} there may be small differences between the address of the instance 
and the `ObjectJc` data part. 
This is if inheritance and virtual tables are used. 
The difference between both address values are stored in the `ObjectJc::offsetToInstanceAddr`, 
which requires setting `DEF_ObjectJcpp_REFLECTION`. If it is not set but 
`DEF_REFLECTION_FULL` is set, and {cpp} compiling is used, then an compiler error message 
is forced (`#error ...`).
The `offsetToInstanceAddr` is necessary to access
data via reflection (`FieldJc`). Hence in {cpp} this form of initializing should be used.
The initializer list is not suitable for use. 

* `SIZE`: The `ObjectJc` part stores the size of the whole instance. Hence it can be tested only with knwoledge of the `ObjectJc` reference whether a safe access to memory is possible with a given reference. Faulty pointer castings can be detected on runtime. It is important that the memory bounds are resepected. Data error because of software errors are acceptable (can be still found), but memory violations causes dubios behavior and ard hard to debug. 

* `ID` The last argument `ID` of the `CTOR_ObjectJc`-Macro is not used in case of `DEF_ObjectJc_SIMPLE`
because the type-ID is stored in the only one `identSize` element. 
But if the `ID` contains the `mArrayId_ObjectJc` flag bit, it is set in the `ObjectJc`. 
It is necessary for the `ObjectArrayJc` which contains the reflection reference to the elements, not for the whole instance. Note that the size information in the `ObjectJc` part is for the whole array, it is always for the whole instance.  

=== Initializing for {cpp}

In {cpp} allocation and construction are combined. It is true in both kinds of creation:

 MyData* data = new MyData(...);
 MyData data(...);  //ctor is invoked with data definition
 
That is a consequent {cpp} feature and prevents errors because of non-initialized data.

But the concept of the `ObjectJc` as core part which contains information 
about the whole instance seems to be primary not regarded. 
Some special constructs and style guides are necessary:

 typedef struct MyType_T {
  union { ObjectJc obj; } base;             //defines ObjectJc as core
  int32 d1; //:Any data
  float d2;  //Note: padding any struct to 8-Byte-align if possible, 
 } MyType_s;

 class MyBaseClass: protected MyType_s      //contains ObjectJc as core
 {
   public: ObjectJc const* const objectJc;
   public: MyBaseClass(ObjectJc const* objectJc);
 }
 
 class MyClass: protected MyBaseClass      //contains ObjectJc as core
 { 
   public: MyClass(int idObj);
   protected: MyClass(ObjectJc const* objectJc);
 }
 
* The both classes can be constructed, but either as instance constructor or as 
constructor for a base class. It is possible to make constructors protected to define
it is only for base class construction.

* A constructor able to use as base constructor should have an argument `ObjectJc* objectJc` anyway.
It is use to call `CTOR_ObjectJc(...)` as argument in the derived constructor.

* The public constructor which should only act as instance constructor have not an `ObjectJc*` argument but it may need an argument for the `idObj`, the ident designation. 
It should call `CTOR_ObjectJc(...)` either in the argument preparation of the base constructor
or in the body of the constructor, if there is not a base class.

Hence the initialization of the `ObjectJc` core part is done firstly in the instance construction `MyClass* ref = new MyClass(myObjId)` : 

 MyClass::MyClass(int idObj) 
   //The public ctor without ObjectJc* argument presumes 
   //that the whole instance should be initialized:
 : MyBaseClass( //the initializer list can only call the ctor of the base class
                //but as argument the CTOR_ObjectJc is called firstly: 
     CTOR_ObjectJc(this->base.obj, this, sizeof(MyClass), refl_MyClass, idObj))
 { //...further init
 }
 
With this system the ObjectJc core data are initialized firstly, which is the concept, 
also for {cpp} situations.
 
The base class constructor can be the instance constructor, or the base constructor. 
It is decide on the argument of othiz: It is set in case of usage as base constructor.
In case of usage as instance constructor it can only be null, because nobody can initialize
the `ObjectJc` part. `MyBaseClass* instance = new MyBaseClass(null);`.  

Additionally the `MyBaseClass` has a const reference `objectJc`, which is need to 
initialize in construction:

 MyBaseClass::MyBaseClass(ObjectJc const* othiz) 
   //The public ctor without ObjectJc* argument presumes 
   //that the whole instance should be initialized:
 : this->objectJc( othiz !=null ? othiz : //either given outside, or:
     CTOR_ObjectJc(&this->base.obj, this, sizeof(*this), refl_MyBaseClass, 0))
 { //...further init
 }


The const `objectJc` reference allows read access to the `ObjectJc` core data
without need of a virtual operation.



== ALLOC_ObjectJc()

The macro-wrapped function call of

 ALLOC_ObjectJc(SIZE, REFL, ID)
 
is for C-usage or for creation of non-`class`-data based on `ObjectJc` in C++.
Depending on `DEF_ObjectJc_SIMPLE` it expands either / or to

 allocReflid_ObjectJc(SIZE, ID_##REFL, ID, _thCxt)
 allocRefl_ObjectJc(SIZE, &(REFL), ID, _thCxt)
 
adequate to `CTOR_ObjectJc` in the chapter above. Additionally it requires the 
pointer to a Thread context 
see link:ThCxtExc_emC.html[Stacktrace, ThreadContext and Exception handling]
because generally the allocation can fail, then an Exception handling is recommended.

The core prototype with reflection reference is
 
 extern_C ObjectJc* alloc_ObjectJc ( const int size, const int32 typeInstanceIdent
                 struct ClassJc_T const* refl  , struct ThreadContext_emC_t* _thCxt);

This routine allocates and initializes the core data of the `ObjectJc`. 
 

[#instanceof]
== Type check for casting and safety

In classic C programming, sometimes in C++ too, often a pointer is stored and/or transferred as `void*`-pointer if the precise type is not known in the transfer or storing environment. 
Before usage a casting to the required type is done. 
*But such casting turns off the compiler error checking capability.* 
An unchecked cast is a leak for source safety.
A void* pointer should only be used for very general things. For example for `memcpy`.

In {cpp} some casting variants are present. The `static_cast<Type*>(ref)` checks on compile time 
whether the cast is admissible in an inheritance of classes, and adjusts the correct
address value toward the start address of the part inside the instance which is adequate to the given type. If there isn't an inheritance relation between the given type and the cast destination type, it forces a compiler error. But the `static_cast<Type*>` does not check 
the really given instance on runtime. On downcast (toward to a derived class) it assumes that the instance is of this type. A upcast (toward to the base class) is always true.

It means the `static_cast<Type*>(ref)` can cause runtime errors if the assumption of the instance type is false.

The `dynamic_cast<Type*>(ref)` does the same for '_downcast_', but additionally the type is checked. This requires activation of RTTI (__RunTime Type Information__). 
If the type is faulty, either a null pointer is delivered or an Exception is thrown, 
depending on the compiler version. 

The `reinterpret_cast<Type*>(ref)` or a ordinary C-Cast `(Type*)(ref)` delivers faulty results if it is used for inheritance class Types. It is an lackadaisical programming error to use reinterpret or C casts for class inheritance. Such an error is inconspicuous so long as no virtual operations are present. Unchecked or lax usage of C-casts or reinterpret-casts are a prone of error. Because a simple C-cast can be used by accident, a {cpp} compiler emits a warning. To assure compatibility between C and {cpp} a macro `CAST_C(Type, ref)` is defined in `emC/Base/types_def_common.h` which is adapted for {cpp} to a `reinterpret_cast<Type*>`.

In C only the known `(Type*)(ref)` written via macro as `C_CAST(Type*, ref)` is available. The capability of static and dynamic casts are only necessary in respect of class hierarchie in {cpp}. The problem is the same: *Unchecked or lax usage of C-casts or reinterpret-casts are a prone of error.* 

Independently of the question C or {cpp} or with or without RTTI 
the `ObjectJc` base class delivers the type information. 
It works for {cpp} too either using the `ObjectJcpp`-Base class 
or with immediate access to the C data which contains `ObjectJc`.
The type check can be done with

 extern_C ClassJc const refl_MyType;
 .....
 bool bTypeOk = instanceof_ObjectJc((&myDataObj->base.obj, &refl_MyType);
 
This routine recognizes and returns `true` for a base type too. 
Note that for class inheritance in {cpp} with multiple inheritance or with virtual operations
a `static_cast<TYPE>(OBJ)` has to be used for cast because addresses should be tuned.
For C inheritance using a base type `struct` as first element of the inherited `struct` 
of course a `C_CAST(TYPE, OBJ)` is only possible and necessary. But the capability
to recognize base types depends on setting and using of `DEF_REFLECTION_FULL` 
in conclusion without definition of `DEF_ObjectJc_SIMPLE` or inside poor applications 
(`DEF_ObjectJc_SIMPLE` is set) with using of `DEF_ObjectJc_REFLREF`. 
See link:Variants_emC.html#refl[Variants of emC-usage in Applications - chapter ClassJc and Reflection].

The cast seems to be safe and might not be necessarily be tested if the type is known 
in the user programming environment, because the
same software module stores the instance pointer, and gets it back.
But there may be programming errors, if the algorithm is enhanced etc.etc.
Hence it is recommended to check the type too, but with an *assertion*, 
which can be switched off for fast runtime request. 
With a side glance to Java the type is always checked on runtime for castings.
In Java a casting error is never possible. 
For that the reflection info in `java.lang.Object` is used.
Because castings are not the operations most commonly used in ordinary programs, 
a little bit of calculation time is admissible for that.

The type check only as safety check, as assertion should be written as: 


 if(CHECK_ASSERT_emC(INSTANCEOF_ObjectJc((&myData->base.obj, reflection_MyType))
               , "faulty instance", 0, 0) { 
   MyType* myData = C_CAST(MyType*, myData);
   ...

The assertion `CHECK_ASSERT_emC(...)` can return always true if assertions are
not activated, for fast realtime. Then the `if(true)` is optimized by the compiler. 
The `C_CAST` is an `reinterpret_cast` for {cpp} usage 
and a normal `((MyType*) myData)` for C usage. 

The `reflection_MyType` is the type information, see next chapter.

If the type of an instance is really unknown, especially if a base reference is delivered
and the derived type should be a point of interest, the 

 if(INSTANCEOF_ObjectJc&myData->base.obj, reflection_MyType) {
   MyType* myDataderived = static_cast<MyType*>(myDate);
   ...
   
can be a part of the functional code. This example shows a {cpp} class reference
where obj is member on. 

For `DEF_ObjectJc_SIMPLE` whereby `ObjectJc` contains only an int32 value 
only the really instance is able to check. 
If the instance in this example is derived from `MyType` the `INSTANCEOF_ObjectJc(...)` 
returns false though the instance has `MyType` as base class. It is a restriction,
but nevertheless often useful. If at least `DEF_ObjectJc_DEFLREF` is defined and 
the reflection are generated via `DEF_REFLECTION_FULL` all information of base types
are contained there. Then `INSTANCEOF_ObjectJc(...)` returns true also for base classes.
Ot is a question of effort and a question of necessities in the application. 

See link:Variants_emC.html#ObjectJc[] and link:ClassJc_en.html[]

[#refl]
== Reflection and Types

In the full capability of `ObjectJc` reflections contains symbolic information 
for all data elements.
A reflection instance of type `ClassJc` contains the type information, 
all base type information and the fields and maybe operations (methods) too.
With the information about base types (super types) the `instanceof_ObjectJc(...)`
can check whether a given instance is proper for a basic type too. 
The construction of full reflection is described in link:ClassJc_en.html#Header2Refl[ClassJc_en, chapter "The reflection generator"]. 

For simple capability of ObjectJc use-able in embedded platforms 
maybe without String processing with fast realtime or less hardware resources 
there are four variant forms of reflections:

* a) In the simplest form, only an `idType` is stored 
which is contained in the ObjectJc instance too to compare it.
In this case the `ClassJc` is defined as:

 typedef struct ClassJc_t {
  int idType;   // sizeReflOffs;
 } ClassJc;
  
* b) Reflection access with Inspector target proxy. In this case reflection data 
are generated in form of positions of data in a `struct` and a number (index) of any 
`struct` type. In this case the `ClassJc` is defined as:

 typedef struct ClassJc_t {
  int idType;   // sizeReflOffs;
  //
  int const* reflOffs;
 } ClassJc;
  
* c) The reference `reflOffs` refers to the generated reflection data. 
As the reflection data are defined in succession in a "const" memory area,
the low 16-bit of this pointer address can be used as a type identifier.

* d) No Reflection access, `DEF_REFLECTION_NO` is set: 
The reflections are only defined to have information about the type:

 typedef struct ClassJc_t {
  int idType;   // sizeReflOffs;
  //
  char const* nameType;
 } ClassJc;
 
The `nameType` is optional depending on `DEF_NO_StringJcCapabilities`. 
See `org/vishia/emC/sourceApplSpecific/SimpleNumCNoExc/ObjectJc_simple.h` 

The kind to build the `idType` depends on some possibilities on initialization
of the `reflection_...Type` instance and can be defined by the users programming. 
For example additional information, which can be used for debugging, are given outside
a fast realtime and low resource CPU, the `idType` is a simple index. 
It is important that the `idType` of all reflection instances are unique.
The `instanceof_ObjectJc(...)` compares only the `idType` given with the `reflection...`
argument with the type information in `ObjectJc`. It is the low 16 bit 
of `idInstanceType` for the simple `ObjectJc`.  

For the reflection with full capability see link:ClassJc_en.html[]. 