= applstdef_emC.h and Variants of C-Usage
:toc:
:sectnums:
:sectlinks:
:cpp: C++

== Why variants are necessary

Software for embedded systems should be run under different conditions:

* very fast realtime
* small memory available
* C or {cpp} usage
* elaborately error checks
* safety or fast

The user software itself should not be changed for this challenges, that is the 
concept of _emC_: _embedded multiplatform C/{cpp}_

[#applstdef]
== applstdef_emC.h to control the variants

The variants can be controlled by the content of a central <applstdef_emC.h> file.
This file contains some settings, may be application specific, 
but some settings are used for the emC sources immediately. 
They are presented in the next chapters.

Additionally some defines can be applied as call arguments of the compiler. 
This is used for the emc_Test because the make scripts are written as Zmake scripts, 
version controlled and obviously visible what is happen. 
For the Test_emC is seems to be proper because a lot of variants should be especially tested.
But usually the defines on the compile line are not obviously visible in version manangement
because compiler control files are often complex (they are the settings of the project in an IDE).

Implementations of the same sources on different platforms may need different variants,
it means different <applstdef_emC.h> each per platform and build configuration. 
This maybe true also on similar PC simulation, and implementation on the same platform 
with different approaches, maybe for the released version 
and a test version with the target platform. 
The different necessary <applstdef.h> should be stored on different paths which are select
by the include path for the different Build configurations.

The emC basic headers regard the variants of compiling conditions. 
The user software can call operations, which may be macros specified to the variants.
*The user software should not regard the variants.* 

One of the basic idea of _emC_ is: *Test in a PC-based high level {cpp} compilation 
environment - and deploy the well tested software on target with the target conditions*.
All sophisticated software checks are done on PC testing, 
the software should be widely error-free after them and can deploy without these checks
on target to run fastly - *without adapting the sources*. 
It means the software can be run and checked again on PC for enhancements, 
without change the sources, and *without sophisticated #ifdef constructs*.  

In conclusion the target compilation and the PC test compilation can or should use 
different variants, for example on PC with exception handling in {cpp} 
which may not available on target.





[#ObjectJc]
== ObjectJc capability

The base `struct` `ObjectJc` is possible as base for some data. 
With this unique base the type and size of data can be evaluate in debugging situations
outside an IDE (data view on target), for evaluating extracted data, and for safety
in an application using type and size checks. 
See link:ObjectJc_en.html[ObjectJc.en.html].

In cohesion with link:Reflection_en.html[Reflection.en.html] the data can be evaluated
without knowledge of the data structure especially for unknown software versions, 
for example in data evaluating situations on legacy software. 
The `ObjectJc` references `ClassJc const* reflection`.

`ObjectJc` as base `struct` also for classes can be used, but does not need to be used
for all data. For the reflection concept only the root class needs the root reference 
to reflection, and especially via interface references the implementation type
can be gotten. 

* `DEF_ObjectJc_SIMPLE`: If that compiler switch is set firstly before other files are
included (in the user specific `<applstdef_emC.h>` or as compiler switch), 
Then the ObjectJc contains only 4 Bytes for a type and size identification. 
The reflection concept is not supported. This variant should be used if very less
RAM is available on the target, but the full ObjectJc capability should be used on
another target or for PC test. Then `ObjectJc` is used as base class, for some data,
but it does not need significant RAM space. 
The application can check the type and size of the data object, 
but only the implementation type, not a supported base type on runtime. 
But note that a proper base type check is supported on compile time in {cpp} 
via `static_cast<BasetType*>(instanceRef)`.

* `DEF_ObjectJc_REFLREF`: If this compiler switch is set
than the `ObjectJc` base `struct` contains the reference to its `ClassJc` reflection  data. 
See link:#refl[chapter Reflection handling]. Only then a base type can be detected
for pointer type casting from a more basically type, especially `ObjectJc*`, 
to a base type of an instance for a C-like or `reinterpret_cast<..>(..)`
It is a similar capability as `dynamic_cast<...>` but without the necessity 
of _RunTimeTypeInformation_ on compiling level. It works for `struct` too
and it works in C. 
For symbolic access (reflection handling) all information are accessible. 
Activating this switch needs additionally 4 bytes for `ObjectJc` in 32-bit-systems.

* `DEF_ObjectJcpp_REFLECTION`: Using reflection in `class` an additional offset between
the position of the partial `ObjectJc` data and the start address of an instance
is necessary. If {cpp} is used with interfaces or multiple inheritance 
and with reflection this switch have to be set. It needs additional 4 bytes. 
But in complex {cpp} systems this amount of memory should be available. 

* `DEF_ObjectJc_SYNCHANDLE`: If this switch is set then the operations 
`synchronized_ObjectJc(..)`, `wait...` and `notify_ObjectJc(..)` and its {cpp}
variants defined in `ObjectJcpp` are available. 
`ObjectJc` contains an index for mutex and notify objects.
It is a Java-adequate concept which associates the handle of operation system resources
for this operations to the data instance. 
It needs the same additional 4 byte as `DEF_ObjectJcpp_REFLECTION` because both information
are stored as two 16 bit words in a 4 byte location, for assurance of 4-byte-boundary.

* `DEF_ObjectJc_OWNADDRESS`: If this switch is set, any ObjectJc partial data 
contains its own address. This is helpfully if data are stored as memory map and 
evaluated. references between data contains the real hardware address references. 
Using the information about the hardware address of own instance the references
can be associated though the data are contained as memory map on other addresses. 

* `DEF_ObjectJc_FULL`: This is a simple switch which forces all capability of `ObjectJc`.
The other switches can be additionally set, but do not need. 
If `DEF_ObjectJc_SIMPLE` is set at once, an `#error message` is forced. 


