/**This file is generated by Cheaer2Refl.jzTc mady by Hartmut Schorrig Version 2020-04-26
 * It contains all defines for generated reflection. 
 */    

#define ID_refl_Test_Ctrl 1
#define ID_refl_Par_PID_Ctrl 2
#define ID_refl_Internal_PID_Ctrl 3
#define ID_refl_PID_Ctrl 4
#define ID_refl_SimTime_emC 5
#define ID_refl_MinMaxCalcTime_emC 6
#define ID_refl_MinMaxTime_emC 7
#define ID_refl_Clock_MinMaxTime_emC 8
#endif //HGUARD_REFLECTION_OFFS
