#ifndef HGUARD_REFLECTION_OFFS
#define HGUARD_REFLECTION_OFFS    
/**This file is generated by Cheaer2Refl.jzTc mady by Hartmut Schorrig Version 2020-04-26
 * It contains all defines for generated reflection. 
 */
#if !defined(DEF_REFLECTION_FULL) && !defined(DEF_REFLECTION_OFFS)
  #define DEF_REFLECTION_OFFS
#endif


#define ID_refl_Base_Test_Ctrl 1
#define DEFINED_refl_Base_Test_Ctrl
#define ID_refl_Test_Ctrl 2
#define DEFINED_refl_Test_Ctrl
#define ID_refl_ParFactors_PIDf_Ctrl_emC 3
#define DEFINED_refl_ParFactors_PIDf_Ctrl_emC
#define ID_refl_Par_PIDf_Ctrl_emC 4
#define DEFINED_refl_Par_PIDf_Ctrl_emC
#define ID_refl_PIDf_Ctrl_emC 5
#define DEFINED_refl_PIDf_Ctrl_emC
#define ID_refl_TimeAbs_emC 6
#define DEFINED_refl_TimeAbs_emC
#define ID_refl_SimTime_emC 7
#define DEFINED_refl_SimTime_emC
#define ID_refl_MinMaxCalcTime_emC 8
#define DEFINED_refl_MinMaxCalcTime_emC
#define ID_refl_MinMaxTime_emC 9
#define DEFINED_refl_MinMaxTime_emC
#define ID_refl_Clock_MinMaxTime_emC 10
#define DEFINED_refl_Clock_MinMaxTime_emC

#endif //HGUARD_REFLECTION_OFFS
