/**This file is generated by Cheaer2Refl.jzTc mady by Hartmut Schorrig Version 2020-04-26
 */
#include <applstdef_emC.h>  //may/should contain following compilerswitch:
#ifdef DEF_REFLECTION_OFFS  //compile this only if DEF_REFLECTION_OFFS should be used 
#include <emC/InspcTargetSimple/Target2Proxy_Inspc.h>  //declares reflectionOffsetArrays
#define protected public    //The access also to private and protected members should be 
#define private public      //  possible here, to calculate its offset.



#include <emC_Exmpl_Ctrl/applstdef_emC.h>  


#include <emC_Exmpl_Ctrl/Test_Ctrl.h>  

int32 const reflectionOffset_Base_Test_Ctrl[] =
{ 1   //index of class in Offset data
, ( ( ((int32)(sizeof(ObjectJc)))<<16 ) | ((int16)(0 + sizeof(ObjectJc)/* offset on bitfield: offset of element before + sizeof(element before) */) & 0x0000ffff) )
};

extern_C ClassJc const refl_Base_Test_Ctrl; //forward declaration because extern "C" 
ClassJc const refl_Base_Test_Ctrl = 
{ 1   //index of class in Offset data    //sizeof(reflectionOffset_Base_Test_Ctrl)
  #ifndef DEF_NO_StringUSAGE
, "Base_Test_Ctrl"
  #endif
, &reflectionOffset_Base_Test_Ctrl[0]
};

int32 const reflectionOffset_Test_Ctrl[] =
{ 2   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, ws)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, ws) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, fT1)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, fT1) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, fs)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, fs) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, sT1)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, sT1) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, sI)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, sI) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, s)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, s) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, par)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, par) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_s, pid)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_s, pid) - OFFSET_IN_STRUCT(Test_Ctrl_s, base.object)) & 0x0000ffff) )
};

extern_C ClassJc const refl_Test_Ctrl; //forward declaration because extern "C" 
ClassJc const refl_Test_Ctrl = 
{ 2   //index of class in Offset data    //sizeof(reflectionOffset_Test_Ctrl)
  #ifndef DEF_NO_StringUSAGE
, "Test_Ctrl"
  #endif
, &reflectionOffset_Test_Ctrl[0]
};


#include <emC_Exmpl_Ctrl/Test_Ctrl_Main.h>  

//#if defined(__cplusplus)
//It is reflection of a class, need to be use C++ compilation anyway.

int32 const reflectionOffset_Test_Ctrl_Main[] =
{ 3   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(Test_Ctrl_Main, stepCt)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Test_Ctrl_Main, stepCt) - OFFSET_IN_STRUCT(Test_Ctrl_Main, base.object)) & 0x0000ffff) )
};

extern_C ClassJc const refl_Test_Ctrl_Main; //forward declaration because extern "C" 
ClassJc const refl_Test_Ctrl_Main = 
{ 3   //index of class in Offset data    //sizeof(reflectionOffset_Test_Ctrl_Main)
  #ifndef DEF_NO_StringUSAGE
, "Test_Ctrl_Main"
  #endif
, &reflectionOffset_Test_Ctrl_Main[0]
};

//#endif //__cplusplus


#include <emC/Ctrl/PIDf_Ctrl_emC.h>  

int32 const reflectionOffset_ParFactors_PIDf_Ctrl_emC[] =
{ 4   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, kP)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, kP) - OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, fTsD)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, fTsD) - OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, fD)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, fD) - OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, fI)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, fI) - OFFSET_IN_STRUCT(ParFactors_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
};

extern_C ClassJc const refl_ParFactors_PIDf_Ctrl_emC; //forward declaration because extern "C" 
ClassJc const refl_ParFactors_PIDf_Ctrl_emC = 
{ 4   //index of class in Offset data    //sizeof(reflectionOffset_ParFactors_PIDf_Ctrl_emC)
  #ifndef DEF_NO_StringUSAGE
, "ParFactors_PIDf_Ctrl_emC"
  #endif
, &reflectionOffset_ParFactors_PIDf_Ctrl_emC[0]
};

int32 const reflectionOffset_Par_PIDf_Ctrl_emC[] =
{ 5   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, ixf)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, ixf) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, en)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, en) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, open)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, open) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, man)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, man) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, _spare_)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, _spare_) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, dbgct_reparam)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, dbgct_reparam) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, Tctrl)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, Tctrl) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, yMax)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, yMax) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, fIx)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, fIx) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, fIy)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, fIy) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, kP)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, kP) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, Tn)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, Tn) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, Td)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, Td) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, T1d)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, T1d) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, f)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, f) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Par_PIDf_Ctrl_emC_s, i)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, i) - OFFSET_IN_STRUCT(Par_PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
};

extern_C ClassJc const refl_Par_PIDf_Ctrl_emC; //forward declaration because extern "C" 
ClassJc const refl_Par_PIDf_Ctrl_emC = 
{ 5   //index of class in Offset data    //sizeof(reflectionOffset_Par_PIDf_Ctrl_emC)
  #ifndef DEF_NO_StringUSAGE
, "Par_PIDf_Ctrl_emC"
  #endif
, &reflectionOffset_Par_PIDf_Ctrl_emC[0]
};

int32 const reflectionOffset_PIDf_Ctrl_emC[] =
{ 6   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, par)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, par) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, limi)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, limi) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, limf)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, limf) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, dwxP)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, dwxP) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, wxP)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, wxP) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, wxPD)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, wxPD) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, yIntg)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, yIntg) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, yctrl)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, yctrl) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, y)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, y) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, yAdd)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, yAdd) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, qI)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, qI) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, qIhi)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, qIhi) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, wxP32)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, wxP32) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, wxPD32)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, wxPD32) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, setIntg)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, setIntg) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, disableIntg)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, disableIntg) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(PIDf_Ctrl_emC_s, _sp_)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, _sp_) - OFFSET_IN_STRUCT(PIDf_Ctrl_emC_s, base.obj)) & 0x0000ffff) )
};

extern_C ClassJc const refl_PIDf_Ctrl_emC; //forward declaration because extern "C" 
ClassJc const refl_PIDf_Ctrl_emC = 
{ 6   //index of class in Offset data    //sizeof(reflectionOffset_PIDf_Ctrl_emC)
  #ifndef DEF_NO_StringUSAGE
, "PIDf_Ctrl_emC"
  #endif
, &reflectionOffset_PIDf_Ctrl_emC[0]
};


#include <emC/Base/Time_emC.h>  

int32 const reflectionOffset_TimeAbs_emC[] =
{ 7   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(TimeAbs_emC, time_sec)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(TimeAbs_emC, time_sec)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(TimeAbs_emC, time_nsec)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(TimeAbs_emC, time_nsec)) & 0x0000ffff) )
};

extern_C ClassJc const refl_TimeAbs_emC; //forward declaration because extern "C" 
ClassJc const refl_TimeAbs_emC = 
{ 7   //index of class in Offset data    //sizeof(reflectionOffset_TimeAbs_emC)
  #ifndef DEF_NO_StringUSAGE
, "TimeAbs_emC"
  #endif
, &reflectionOffset_TimeAbs_emC[0]
};

int32 const reflectionOffset_SimTime_emC[] =
{ 8   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(SimTime_emC, timeShort)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(SimTime_emC, timeShort)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(SimTime_emC, spare1_8aligned)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(SimTime_emC, spare1_8aligned)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(SimTime_emC, timeSim)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(SimTime_emC, timeSim)) & 0x0000ffff) )
};

extern_C ClassJc const refl_SimTime_emC; //forward declaration because extern "C" 
ClassJc const refl_SimTime_emC = 
{ 8   //index of class in Offset data    //sizeof(reflectionOffset_SimTime_emC)
  #ifndef DEF_NO_StringUSAGE
, "SimTime_emC"
  #endif
, &reflectionOffset_SimTime_emC[0]
};

int32 const reflectionOffset_MinMaxCalcTime_emC[] =
{ 9   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxCalcTime_emC, minCalcTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxCalcTime_emC, minCalcTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxCalcTime_emC, ctSpikes)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxCalcTime_emC, ctSpikes)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxCalcTime_emC, midCalcTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxCalcTime_emC, midCalcTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxCalcTime_emC, actCalcTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxCalcTime_emC, actCalcTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxCalcTime_emC, maxCalcTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxCalcTime_emC, maxCalcTime)) & 0x0000ffff) )
};

extern_C ClassJc const refl_MinMaxCalcTime_emC; //forward declaration because extern "C" 
ClassJc const refl_MinMaxCalcTime_emC = 
{ 9   //index of class in Offset data    //sizeof(reflectionOffset_MinMaxCalcTime_emC)
  #ifndef DEF_NO_StringUSAGE
, "MinMaxCalcTime_emC"
  #endif
, &reflectionOffset_MinMaxCalcTime_emC[0]
};

int32 const reflectionOffset_MinMaxTime_emC[] =
{ 10   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, ct)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, ct)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, _lastTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, _lastTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, minCyclTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, minCyclTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, actCyclTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, actCyclTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, midCyclTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, midCyclTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, maxCyclTime)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, maxCyclTime)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MinMaxTime_emC, calc)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MinMaxTime_emC, calc)) & 0x0000ffff) )
};

extern_C ClassJc const refl_MinMaxTime_emC; //forward declaration because extern "C" 
ClassJc const refl_MinMaxTime_emC = 
{ 10   //index of class in Offset data    //sizeof(reflectionOffset_MinMaxTime_emC)
  #ifndef DEF_NO_StringUSAGE
, "MinMaxTime_emC"
  #endif
, &reflectionOffset_MinMaxTime_emC[0]
};

int32 const reflectionOffset_Clock_MinMaxTime_emC[] =
{ 11   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(Clock_MinMaxTime_emC, microSecondsPerClock)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Clock_MinMaxTime_emC, microSecondsPerClock) - OFFSET_IN_STRUCT(Clock_MinMaxTime_emC, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Clock_MinMaxTime_emC, nrofSlices)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Clock_MinMaxTime_emC, nrofSlices) - OFFSET_IN_STRUCT(Clock_MinMaxTime_emC, base.object)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(Clock_MinMaxTime_emC, times)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(Clock_MinMaxTime_emC, times) - OFFSET_IN_STRUCT(Clock_MinMaxTime_emC, base.object)) & 0x0000ffff) )
};

extern_C ClassJc const refl_Clock_MinMaxTime_emC; //forward declaration because extern "C" 
ClassJc const refl_Clock_MinMaxTime_emC = 
{ 11   //index of class in Offset data    //sizeof(reflectionOffset_Clock_MinMaxTime_emC)
  #ifndef DEF_NO_StringUSAGE
, "Clock_MinMaxTime_emC"
  #endif
, &reflectionOffset_Clock_MinMaxTime_emC[0]
};

int32 const reflectionOffset_MeasRunTimeFBlock[] =
{ 12   //index of class in Offset data
, ( ( ((int32)(SIZEOF_IN_STRUCT(MeasRunTimeFBlock_s, nrExec)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MeasRunTimeFBlock_s, nrExec)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MeasRunTimeFBlock_s, whatExec)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MeasRunTimeFBlock_s, whatExec)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MeasRunTimeFBlock_s, val1)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MeasRunTimeFBlock_s, val1)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MeasRunTimeFBlock_s, val2)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MeasRunTimeFBlock_s, val2)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MeasRunTimeFBlock_s, valf1)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MeasRunTimeFBlock_s, valf1)) & 0x0000ffff) )
, ( ( ((int32)(SIZEOF_IN_STRUCT(MeasRunTimeFBlock_s, valf2)))<<16 ) | ((int16)(OFFSET_IN_STRUCT(MeasRunTimeFBlock_s, valf2)) & 0x0000ffff) )
};

extern_C ClassJc const refl_MeasRunTimeFBlock; //forward declaration because extern "C" 
ClassJc const refl_MeasRunTimeFBlock = 
{ 12   //index of class in Offset data    //sizeof(reflectionOffset_MeasRunTimeFBlock)
  #ifndef DEF_NO_StringUSAGE
, "MeasRunTimeFBlock"
  #endif
, &reflectionOffset_MeasRunTimeFBlock[0]
};


/**Array of pointer to all refl_Type definition.
 * The order of the pointer matches to the ClassJc#index
 * The target2proxy service accesses the correct ClassJc by given index in communication.
 */
ClassJc const* const reflectionOffsetArrays[] =
{ null  //index 0 left free 
, &refl_Base_Test_Ctrl
, &refl_Test_Ctrl
, &refl_Test_Ctrl_Main
, &refl_ParFactors_PIDf_Ctrl_emC
, &refl_Par_PIDf_Ctrl_emC
, &refl_PIDf_Ctrl_emC
, &refl_TimeAbs_emC
, &refl_SimTime_emC
, &refl_MinMaxCalcTime_emC
, &refl_MinMaxTime_emC
, &refl_Clock_MinMaxTime_emC
, &refl_MeasRunTimeFBlock

};

#endif //DEF_REFLECTION_OFFS
